spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: ""

ibkr:
  urls:
    generateReport: https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/SendRequest
    getReport: https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/GetStatement
  secrets:
    flexToken: flexToken
    flexQueryId: flexQueryId

jwt:
  secret: secret
  expiration: 3600000
